---
title: 托管线程中的异常
date: 2021-10-22 14:10:21
tags:
---

## 托管线程中的异常

> 公共语言运行时允许线程中的多数未经处理的异常正常继续。在多数情况下，这意味者未经处理的异常会导致应用程序终止。

公共语言运行时为用于控制程序流的某些未经处理的异常提供支持：

- 由于Abort得到调用，因此`ThreadAbortException`在线程中抛出
- 由于线程执行时所在的应用域正在卸载，因此`AppDomainUnloadedException`在线程中抛出
- 公共语言运行时或主机进程通过引发内部异常来终止线程
  
如果公共语言运行时所创建的线程中未处理这些异常中的任何一个，则异常会终止线程，但公共语言运行时不允许该异常继续下去。

如果在主线程或从非托管代码进入运行时的线程中未处理这些异常，则它们会正常继续，并导致应用终止。
